---
- name: Execute Terraform Plan using Ansible Automation Platform
  hosts: all
  tasks:
  
  - name: initializating and applying Terraform Project 
  terraform:
      project_path: '{{ project_dir }}/'
      state: "{{ state }}"
      force_init: true
